-- Rian AI Gen 2 durable account store
-- Run this once in Supabase SQL Editor.
-- The Flask server uses the SERVICE ROLE key, so browser clients never access this table.

create table if not exists public.rian_users (
  id bigint generated by default as identity primary key,
  username_key text not null unique,
  username text not null,
  password_hash text not null,
  student jsonb not null default '{}'::jsonb,
  sessions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists rian_users_username_key_idx
  on public.rian_users (username_key);

-- Keep the table private to the public client. Rian talks to it server-side
-- using the Supabase service-role key.
alter table public.rian_users enable row level security;

-- No anon/authenticated policies are created intentionally.
-- The service-role key bypasses RLS and must NEVER be exposed to the browser.
